name: taskline
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.7.2 # routing
  flutter_svg: ^2.0.17 # for svg images

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/lottie/
  fonts:
    - family: ALSPofo-Bold
      fonts:
        - asset: assets/fonts/ALSPofo-Bold.ttf
    - family: ALSPofo-Regular
      fonts:
        - asset: assets/fonts/ALSPofo-Regular.ttf
    - family: ALSPofo-Light
      fonts:
        - asset: assets/fonts/ALSPofo-Light.ttf
    - family: ONY-FORM-Medium
      fonts:
        - asset: assets/fonts/ONY-FORM-Medium.ttf
    - family: ONY-FORM-Regular
      fonts:
        - asset: assets/fonts/ONY-FORM-Regular.ttf
    - family: Raleway-SemiBold
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Raleway-ExtraBold
      fonts:
        - asset: assets/fonts/Raleway-ExtraBold.ttf
    - family: Raleway-Black
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
    - family: Raleway-Light
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
    - family: Raleway-Medium
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: Raleway-Regular
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Nunito-Black
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito-ExtraBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf
    - family: Nunito-ExtraLight
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
    - family: Nunito-Light
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
    - family: Nunito-Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Nunito-SemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
