name: taskline
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.7.2 # routing
  flutter_svg: ^2.0.17 # for svg images
  google_nav_bar: ^5.0.7 # navigation bar
  line_icons: ^2.0.3 # icon set

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito.ttf
    - family: Raleway-SemiBold
      fonts:
        - asset: assets/fonts/Raleway-SemiBold.ttf
    - family: Raleway-Bold
      fonts:
        - asset: assets/fonts/Raleway-Bold.ttf
    - family: Raleway-ExtraBold
      fonts:
        - asset: assets/fonts/Raleway-ExtraBold.ttf
    - family: Raleway-Black
      fonts:
        - asset: assets/fonts/Raleway-Black.ttf
    - family: Raleway-Light
      fonts:
        - asset: assets/fonts/Raleway-Light.ttf
    - family: Raleway-Medium
      fonts:
        - asset: assets/fonts/Raleway-Medium.ttf
    - family: Raleway-Regular
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
    - family: Nunito-Black
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
    - family: Nunito-Bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
    - family: Nunito-ExtraBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf
    - family: Nunito-ExtraLight
      fonts:
        - asset: assets/fonts/Nunito-ExtraLight.ttf
    - family: Nunito-Light
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
    - family: Nunito-Medium
      fonts:
        - asset: assets/fonts/Nunito-Medium.ttf
    - family: Nunito-Regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
    - family: Nunito-SemiBold
      fonts:
        - asset: assets/fonts/Nunito-SemiBold.ttf
    - family: Nunito-VariableFont_wght
